<?php

namespace Afandi\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BukuTamuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BukuTamuRepository extends EntityRepository
{
	public function findAllBukuTamuPagination()
    {
        $repository = $this->getEntityManager()
            ->getRepository('AfandiMainBundle:BukuTamu');

        $query = $repository->createQueryBuilder('bukutamu')
            ->getQuery();

        return $query;
    }
}
